/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SCAN_H_RPCGEN
#define _SCAN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct File_res {
	int chars;
	int words;
	int lines;
};
typedef struct File_res File_res;

struct Dir_input {
	char *dir;
	int soglia;
};
typedef struct Dir_input Dir_input;

#define SCANPROG 0x20000020
#define SCANVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILE_SCAN 1
extern  File_res * file_scan_1(char **, CLIENT *);
extern  File_res * file_scan_1_svc(char **, struct svc_req *);
#define DIR_SCAN 2
extern  int * dir_scan_1(Dir_input *, CLIENT *);
extern  int * dir_scan_1_svc(Dir_input *, struct svc_req *);
extern int scanprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILE_SCAN 1
extern  File_res * file_scan_1();
extern  File_res * file_scan_1_svc();
#define DIR_SCAN 2
extern  int * dir_scan_1();
extern  int * dir_scan_1_svc();
extern int scanprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_File_res (XDR *, File_res*);
extern  bool_t xdr_Dir_input (XDR *, Dir_input*);

#else /* K&R C */
extern bool_t xdr_File_res ();
extern bool_t xdr_Dir_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SCAN_H_RPCGEN */
