/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "scan.h"

bool_t
xdr_File_res (XDR *xdrs, File_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->chars))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->words))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->lines))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Dir_input (XDR *xdrs, Dir_input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->dir, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->soglia))
		 return FALSE;
	return TRUE;
}
